import type { Metadata } from "next";
import { Jost } from "next/font/google";

import { cn } from "@/lib/utils";
import { Footer } from "@/modules/layout/components/footer";
import { Header } from "@/modules/layout/components/header";

import "./globals.css";

const font = Jost({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: React.PropsWithChildren) {
  return (
    <html lang="en">
      <body className={cn("antialiased", font.className)}>
        <div className="flex min-h-screen flex-col">
          <Header />
          <main className="flex-1">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
